module.exports =  {
    "reviewed-companies": "Empresas Recientemente Revisadas [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "recently-rated": "Compañías Recientemente Calificadas [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "answered-questions": "Preguntas y Respuestas Recientemente Respondidas [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "with-candidates": "Empresas Populares [local:sizeLabel] Para Trabajar [local:alphaFilter] [local:inLabel] [local:cityLabel] ",
    "with-questions": "Preguntas y Respuestas de la Compañía [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "not-rated": "Aún no calificado [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "all": "Todas las Empresas [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated": "Las Empresas Mejor Calificadas [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-ceos": "CEOs Mejor Calificados [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-for-women": "Compañías Mejor Calificadas Para Mujeres [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-for-diversity": "Compañías Mejor Calificadas Para la Diversidad [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-enps": "eNPS Mejor Calificados [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-report-card": "Cultura mejor valorada [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-compensation": "Compensación nominal superior [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-vs-competitors": "Mejor calificados vs. competidores [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-team": "Equipo mejor calificado [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-executive-team": "Equipo ejecutivo mejor calificado [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "browse-company-salaries": "Buscar salarios por empresa [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "label_byMetro": "por Metros",
    "label_in": "en",
    "label_others": "Otros",
};