module.exports =  {
    "reviewed-companies": "Recently Reviewed Companies [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "recently-rated": "Recently Rated Companies [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "answered-questions": "Recently Answered Q&A [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "with-candidates": "Popular Companies [local:sizeLabel] to Work For [local:alphaFilter] [local:inLabel] [local:cityLabel] ",
    "with-questions": "Company Q&A [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "not-rated": "Not Yet Rated [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "all": "All Companies [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated": "Top Rated Companies [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-ceos": "Top Rated CEOs [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-for-women": "Top Rated Companies for Women [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-for-diversity": "Top Rated Companies for Diversity [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-enps": "Top Rated eNPS [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-report-card": "Top Rated Culture [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-compensation": "Top Rated Compensation [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-vs-competitors": "Top Rated vs. Competitors [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-team": "Top Rated Team [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "top-rated-executive-team": "Top Rated Executive Team [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "browse-company-salaries": "Browse Salaries by Company [local:alphaFilter] [local:sizeLabel] [local:inLabel] [local:cityLabel] ",
    "label_byMetro": "by Metros",
    "label_in": "in",
    "label_others": "Others",
};