module.exports = {
    label_allCompanies: "All Companies",
    label_topRatedCompaniesByMetro: "Top Rated Companies by Metro",
    label_topRatedCEOs: "Top Rated CEOs",
    label_topRatedForWomen: "Top Rated for Women",
    label_topRatedForDiverseEmployees: "Top Rated for Diverse Employees",
    label_topRatedENPS: "Top Rated eNPS",
    label_topRatedReportCard: "Top Rated Report Card",
    label_topRatedVSCompetitors: "Top Rated vs Competitors",
    label_topRatedTeams: "Top Rated Teams",
    label_recentlyReviewedCompanies: "Recently Reviewed Companies",
    label_recentlyAnsweredQNA: "Recently Answered Q&A",
    label_companiesWithTheMostCandidates: "Companies with the Most Candidates",
    label_companiesWithTheMostEmployeeQNA: "Companies with the Most Employee Q&A",
    label_topRatedForCompensation: "Top Rated for Compensation",
    label_topRatedForExecutiveTeam: "Top Rated for Executive Team",
    label_recentlyRatedCompanies: "Recently Rated Companies",
    label_notYetRated: "Not Yet Rated",
    label_browseSalariesByCompany: "Browse Salaries by Company",
};