module.exports = {
    label_allCompanies: "Todas las Empresas",
    label_topRatedCompaniesByMetro: "Las Empresas Mejor Calificadas por Metro",
    label_topRatedCEOs: "CEOs Mejor Calificados",
    label_topRatedForWomen: "Mejor Calificadas para Mujeres",
    label_topRatedForDiverseEmployees: "Mejor Calificada para Empleados Diversos",
    label_topRatedENPS: "eNPS Mejor Calificados",
    label_topRatedReportCard: "Boleta de Calificaciones de Mejor Calificado",
    label_topRatedVSCompetitors: "Los Mejores Clasificados Frente a los Competidores",
    label_topRatedTeams: "Equipos Mejor Calificados",
    label_recentlyReviewedCompanies: "Empresas Recientemente Revisadas",
    label_recentlyAnsweredQNA: "Preguntas y Respuestas Recientemente Respondidas",
    label_companiesWithTheMostCandidates: "Las Empresas con Más Candidatos",
    label_companiesWithTheMostEmployeeQNA: "Las Empresas con Más Preguntas y Respuestas de los Empleados",
    label_topRatedForCompensation: "Mejor Calificados por Salario",
    label_topRatedForExecutiveTeam: "Mejor Calificados por Equipo Ejecutivo",
    label_recentlyRatedCompanies: "Empresas Recientemente Calificadas",
    label_notYetRated: "Aún no Calificado",
    label_browseSalariesByCompany: "Buscar Salarios por Empresa",
};
