module.exports = {
    "1" : "Cuenta Propia",
    "2" : "1-10 Empleados",
    "3" : "11-50 Empleados",
    "4" : "51-200 Empleados",
    "5" : "201-500 Empleados",
    "6" : "501-1,000 Empleados",
    "7" : "1,001-5,000 Empleados",
    "8" : "5,001-10,000 Empleados",
    "9" : "10,000+ Empleados",

    "short_1" : "1",
    "short_2" : "1-10",
    "short_3" : "11-50",
    "short_4" : "51-200",
    "short_5" : "201-500",
    "short_6" : "501-1k",
    "short_7" : "1k-5k",
    "short_8" : "5k-10k",
    "short_9" : "10k+",

    "example_1" : "",
    "example_2" : "Empresas Como <b>Forward</b>, <b>Joymode</b>, <b>PlateJoy</b>, <b>Flo</b>",
    "example_3" : "Empresas Como <b>Product Hunt</b>, <b>Rinse</b>, <b>The Bouqs</b>, <b>Cheddar</b>",
    "example_4" : "Empresas Como <b>Soylent</b>, <b>ClassPass</b>, <b>Laurel & Wolf</b>, <b>Musical.ly</b>",
    "example_5" : "Empresas Como <b>Evernote</b>, <b>Postmates</b>, <b>The Honest Company</b>, <b>Dollar Shave Club</b>",
    "example_6" : "Empresas Como <b>InstaCart</b>, <b>Oculus</b>, <b>Warby Parker</b>, <b>Slack</b>",
    "example_7" : "Empresas Como <b>Snap Inc.</b>, <b>Airbnb</b>, <b>Square</b>, <b>Netflix</b>",
    "example_8" : "Empresas Como <b>Uber</b>, <b>Intuit</b>, <b>WhatsApp</b>, <b>Electronic Arts</b>",
    "example_9" : "Empresas Como <b>Facebook</b>, <b>Google</b>, <b>Apple</b>, <b>Amazon</b>",

    "sized_1" : "Clasifican 1",
    "sized_2" : "Clasifican 1-10",
    "sized_3" : "Clasifican 11-50",
    "sized_4" : "Clasifican 51-200",
    "sized_5" : "Clasifican 201-500",
    "sized_6" : "Clasifican 501-1,000",
    "sized_7" : "Clasifican 1,001-5,000",
    "sized_8" : "Clasifican 5,001-10,000",
    "sized_9" : "Clasifican 10,000+",

};
