module.exports = {
    "1" : "Self Employed",
    "2" : "1-10 Employees",
    "3" : "11-50 Employees",
    "4" : "51-200 Employees",
    "5" : "201-500 Employees",
    "6" : "501-1,000 Employees",
    "7" : "1,001-5,000 Employees",
    "8" : "5,001-10,000 Employees",
    "9" : "10,000+ Employees",

    "short_1" : "1",
    "short_2" : "1-10",
    "short_3" : "11-50",
    "short_4" : "51-200",
    "short_5" : "201-500",
    "short_6" : "501-1k",
    "short_7" : "1k-5k",
    "short_8" : "5k-10k",
    "short_9" : "10k+",

    "example_1" : "",
    "example_2" : "Companies Like <b>Forward</b>, <b>Joymode</b>, <b>PlateJoy</b>, <b>Flo</b>",
    "example_3" : "Companies Like <b>Product Hunt</b>, <b>Rinse</b>, <b>The Bouqs</b>, <b>Cheddar</b>",
    "example_4" : "Companies Like <b>Soylent</b>, <b>ClassPass</b>, <b>Laurel & Wolf</b>, <b>Musical.ly</b>",
    "example_5" : "Companies Like <b>Evernote</b>, <b>Postmates</b>, <b>The Honest Company</b>, <b>Dollar Shave Club</b>",
    "example_6" : "Companies Like <b>InstaCart</b>, <b>Oculus</b>, <b>Warby Parker</b>, <b>Slack</b>",
    "example_7" : "Companies Like <b>Snap Inc.</b>, <b>Airbnb</b>, <b>Square</b>, <b>Netflix</b>",
    "example_8" : "Companies Like <b>Uber</b>, <b>Intuit</b>, <b>WhatsApp</b>, <b>Electronic Arts</b>",
    "example_9" : "Companies Like <b>Facebook</b>, <b>Google</b>, <b>Apple</b>, <b>Amazon</b>",

    "sized_1" : "Sized 1",
    "sized_2" : "Sized 1-10",
    "sized_3" : "Sized 11-50",
    "sized_4" : "Sized 51-200",
    "sized_5" : "Sized 201-500",
    "sized_6" : "Sized 501-1,000",
    "sized_7" : "Sized 1,001-5,000",
    "sized_8" : "Sized 5,001-10,000",
    "sized_9" : "Sized 10,000+",

};
