module.exports = {
    tooltip_text: "Comparado con otras empresas de tamaño similar en [local:metroName]",
    tooltip_text_noMetro: "Comparado con otras empresas de tamaño similar en EUA",
    tooltip_text_noMetro_noCountry: "Comparado con otras empresas de tamaño similar",

    leadershipSummary_header_CEORating: "Calificación del CEO",
    leadershipSummary_text_CEORating: "[local:ceoName], el CEO de [local:companyName] recibió una calificación promedio de <b class=\"score\">[local:score]</b> de <b class=\"count\">[local:participants]</b> empleados de [local:companyName].",
    leadershipSummary_text_noName_CEORating: "El CEO de [local:companyName] recibió una calificación promedio de <b>[local:score]</b> de empleados de [local:companyName].",
    leadershipSummary_gender_CEORating: "Los empleados <b>[local:gender_high]</b> en [local:companyName] califican al CEO más alto.",
    leadershipSummary_departmentId_CEORating: "El departamento de <b>[local:departmentId_high]</b> en [local:companyName] califica al CEO más alto, mientras que el Departamento de <b>[local:departmentId_low]</b> califica al CEO más bajo.",
    leadershipSummary_departmentId_noLow_CEORating: "El departamento de <b>[local:departmentId_high]</b> en [local:companyName] califica al CEO más alto.",
    leadershipSummary_tenure_CEORating: "Los empleados que han estado en [local:companyName] durante <b>[local:tenure_high]</b> califican al CEO más alto.",
    leadershipSummary_ethnicity_CEORating: "Los empleados [local:ethnicity_high] en [local:companyName] califican al CEO más alto.",

    leadershipSummary_header_Manager: "Calificación del Gerente",
    leadershipSummary_text_Manager: "Los gerentes recibieron un puntaje promedio de <b class=\"score\">[local:score]</b> de <b class=\"count\">[local:participants]</b> empleados de [local:companyName].",
    leadershipSummary_gender_Manager: "Los empleados <b>[local:gender_high]</b> en [local:companyName] califican a su gerente más alto.",
    leadershipSummary_departmentId_Manager: "El departamento de <b>[local:departmentId_high]</b> en [local:companyName] califica a su Gerente más alto, mientras que el Departamento de <b>[local:departmentId_low]</b> califica a su Gerente más bajo.",
    leadershipSummary_departmentId_noLow_Manager: "El departamento de <b>[local:departmentId_high]</b> en [local:companyName] califica a su Gerente más alto.",
    leadershipSummary_tenure_Manager: "Los empleados que han estado en [local:companyName] durante <b>[local:tenure_high]</b> califican a su gerente más alto.",
    leadershipSummary_ethnicity_Manager: "Los empleados [local:ethnicity_high] de [local:companyName] califican a su gerente más alto.",

    leadershipSummary_header_ExecutiveTeam: "Calificación del Equipo Ejecutivo",
    leadershipSummary_text_ExecutiveTeam: "El equipo ejecutivo recibió un puntaje promedio de <b class=\"score\">[local:score]</b> de <b class=\"count\">[local:participants]</b> empleados de [local:companyName].",
    leadershipSummary_gender_ExecutiveTeam: "Los empleados <b>[local:gender_high]</b> en [local:companyName] califican al equipo ejecutivo más alto.",
    leadershipSummary_departmentId_ExecutiveTeam: "El departamento de <b>[local:departmentId_high]</b> en [local:companyName] califica al Equipo Ejecutivo más alto, mientras que el Departamento de <b>[local:departmentId_low]</b> califica al Equipo Ejecutivo más bajo.",
    leadershipSummary_departmentId_noLow_ExecutiveTeam: "El departamento de <b>[local:departmentId_high]</b> en [local:companyName] califica al Equipo Ejecutivo más alto.",
    leadershipSummary_tenure_ExecutiveTeam: "Los empleados que han estado en [local:companyName] durante <b>[local:tenure_high]</b> califican al equipo ejecutivo más alto.",
    leadershipSummary_ethnicity_ExecutiveTeam: "Los empleados [local:ethnicity_high] en [local:companyName] califican al equipo ejecutivo más alto.",
};
